# Generated by Django 4.0.5 on 2022-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_student_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
